
set search_path = public, extensions;

-- Extend points ledger types for horse racing flows.
alter table public.points_transactions add column if not exists game_type text;
alter table public.points_transactions drop constraint if exists points_transactions_type_check;
alter table public.points_transactions add constraint points_transactions_type_check check (
  type in (
    'bet_lock', 'bet_win', 'bet_loss', 'admin_adjust', 'daily_claim', 'round_cancel',
    'poker_bet_lock', 'poker_bet_win', 'poker_bet_loss', 'poker_round_refund',
    'buy_in_lock', 'win_pot', 'refund',
    'spin_bet', 'spin_win',
    'horse_bet_lock', 'horse_bet_win', 'horse_bet_loss', 'horse_refund'
  )
);

create table if not exists public.horse_race_settings (
  settings_id smallint primary key default 1 check (settings_id = 1),
  enabled boolean not null default true,
  min_bet integer not null default 10 check (min_bet >= 1),
  max_bet integer not null default 100000 check (max_bet >= min_bet),
  betting_duration integer not null default 30 check (betting_duration between 10 and 180),
  race_duration integer not null default 30 check (race_duration between 10 and 180),
  updated_by uuid references public.users(uid) on delete set null,
  updated_at timestamptz not null default now(),
  version integer not null default 1
);

alter table public.horse_race_settings
  alter column race_duration set default 30;
alter table public.horse_race_settings
  drop constraint if exists horse_race_settings_race_duration_check;
alter table public.horse_race_settings
  drop constraint if exists horse_race_settings_betting_duration_check;
update public.horse_race_settings
set race_duration = greatest(10, least(coalesce(race_duration, 30), 180))
where race_duration is distinct from greatest(10, least(coalesce(race_duration, 30), 180));
update public.horse_race_settings
set betting_duration = greatest(10, least(coalesce(betting_duration, 30), 180))
where betting_duration is distinct from greatest(10, least(coalesce(betting_duration, 30), 180));
alter table public.horse_race_settings
  add constraint horse_race_settings_race_duration_check check (race_duration between 10 and 180) not valid;
alter table public.horse_race_settings
  add constraint horse_race_settings_betting_duration_check check (betting_duration between 10 and 180) not valid;
alter table public.horse_race_settings validate constraint horse_race_settings_race_duration_check;
alter table public.horse_race_settings validate constraint horse_race_settings_betting_duration_check;

insert into public.horse_race_settings (settings_id)
values (1)
on conflict (settings_id) do nothing;

create table if not exists public.horses (
  horse_id uuid primary key default gen_random_uuid(),
  name text not null,
  avatar text,
  speed_rating integer not null default 50 check (speed_rating between 1 and 100),
  rarity text not null default 'common' check (rarity in ('common', 'rare', 'epic', 'legendary')),
  odds_multiplier numeric(10,4) not null check (odds_multiplier >= 1),
  win_probability numeric(10,4) not null check (win_probability >= 0),
  enabled boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.horses
  drop constraint if exists horses_odds_multiplier_check;
update public.horses
set odds_multiplier = 1
where odds_multiplier < 1;
alter table public.horses
  add constraint horses_odds_multiplier_check check (odds_multiplier >= 1) not valid;
alter table public.horses validate constraint horses_odds_multiplier_check;

create table if not exists public.horse_races (
  race_id uuid primary key default gen_random_uuid(),
  race_number bigint generated by default as identity,
  status text not null default 'betting' check (status in ('waiting', 'betting', 'locked', 'racing', 'completed', 'cancelled')),
  winner_horse_id uuid references public.horses(horse_id) on delete set null,
  horses_snapshot jsonb not null default '[]'::jsonb,
  settings_version integer not null default 1,
  betting_started_at timestamptz not null default now(),
  betting_ends_at timestamptz not null,
  locked_at timestamptz,
  lock_ends_at timestamptz,
  race_started_at timestamptz,
  race_ends_at timestamptz,
  started_at timestamptz,
  ended_at timestamptz,
  created_by uuid references public.users(uid) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint horse_races_timeline check (betting_ends_at >= betting_started_at)
);

create table if not exists public.horse_bets (
  bet_id uuid primary key default gen_random_uuid(),
  race_id uuid not null references public.horse_races(race_id) on delete cascade,
  user_id uuid not null references public.users(uid) on delete cascade,
  horse_id uuid not null references public.horses(horse_id) on delete restrict,
  bet_amount integer not null check (bet_amount >= 1),
  odds_multiplier numeric(10,4) not null check (odds_multiplier >= 0),
  status text not null default 'pending' check (status in ('pending', 'settled', 'cancelled')),
  result text check (result in ('win', 'lose')),
  payout integer not null default 0,
  points_before integer,
  points_after integer,
  points_change integer not null default 0,
  settled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (race_id, user_id, horse_id),
  constraint horse_bets_result_state check (
    (status = 'pending' and result is null)
    or (status = 'settled' and result in ('win', 'lose'))
    or (status = 'cancelled' and result is null)
  )
);

create table if not exists public.horse_chat_messages (
  message_id uuid primary key default gen_random_uuid(),
  user_id uuid references public.users(uid) on delete set null,
  display_name text not null,
  avatar text,
  role text not null default 'user' check (role in ('user', 'admin', 'system')),
  vip_level smallint not null default 0 check (vip_level between 0 and 10),
  text text not null check (char_length(text) between 1 and 300),
  is_system boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by uuid references public.users(uid) on delete set null,
  is_deleted boolean not null default false
);

create table if not exists public.horse_player_stats (
  user_id uuid primary key references public.users(uid) on delete cascade,
  account_name text not null,
  display_name text not null,
  avatar_url text,
  total_winnings bigint not null default 0,
  biggest_win integer not null default 0,
  total_bets integer not null default 0,
  win_count integer not null default 0,
  best_streak integer not null default 0,
  current_streak integer not null default 0,
  updated_at timestamptz not null default now()
);

create index if not exists horse_races_status_created_idx on public.horse_races (status, created_at desc);
create index if not exists horse_bets_race_status_idx on public.horse_bets (race_id, status);
create index if not exists horse_bets_user_created_idx on public.horse_bets (user_id, created_at desc);
create index if not exists horse_chat_created_idx on public.horse_chat_messages (created_at desc);
create index if not exists horse_stats_winnings_idx on public.horse_player_stats (total_winnings desc, updated_at asc);

create or replace function public.horse_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_horses_updated_at on public.horses;
create trigger set_horses_updated_at
  before update on public.horses
  for each row
  execute function public.horse_set_updated_at();

drop trigger if exists set_horse_races_updated_at on public.horse_races;
create trigger set_horse_races_updated_at
  before update on public.horse_races
  for each row
  execute function public.horse_set_updated_at();

drop trigger if exists set_horse_bets_updated_at on public.horse_bets;
create trigger set_horse_bets_updated_at
  before update on public.horse_bets
  for each row
  execute function public.horse_set_updated_at();

drop trigger if exists set_horse_chat_messages_updated_at on public.horse_chat_messages;
create trigger set_horse_chat_messages_updated_at
  before update on public.horse_chat_messages
  for each row
  execute function public.horse_set_updated_at();

insert into public.horses (name, avatar, speed_rating, rarity, odds_multiplier, win_probability, enabled, sort_order)
select *
from (
  values
    ('Thunder Bolt', '/assets/horses/neon-horse.svg', 86, 'rare', 1.8::numeric, 30::numeric, true, 1),
    ('Shadow King', '/assets/horses/neon-horse.svg', 82, 'epic', 2.4::numeric, 24::numeric, true, 2),
    ('Red Fury', '/assets/horses/neon-horse.svg', 78, 'common', 3.2::numeric, 20::numeric, true, 3),
    ('Silver Wind', '/assets/horses/neon-horse.svg', 75, 'rare', 4.8::numeric, 16::numeric, true, 4),
    ('Dark Flame', '/assets/horses/neon-horse.svg', 72, 'legendary', 6.5::numeric, 10::numeric, true, 5)
) as defaults(name, avatar, speed_rating, rarity, odds_multiplier, win_probability, enabled, sort_order)
where not exists (select 1 from public.horses);

update public.horses
set avatar = '/assets/horses/neon-horse.svg'
where nullif(trim(coalesce(avatar, '')), '') is null;
create or replace function public.horse_validate_horses_config()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  enabled_count integer;
  total_probability numeric(14,4);
begin
  select count(*), coalesce(sum(h.win_probability), 0)
  into enabled_count, total_probability
  from public.horses h
  where h.enabled = true;

  if enabled_count < 5 or enabled_count > 10 then
    raise exception 'Horse racing requires 5-10 enabled horses, found %', enabled_count using errcode = '22023';
  end if;

  if abs(total_probability - 100) > 0.0001 then
    raise exception 'Enabled horse probabilities must total 100%%, got %', total_probability using errcode = '22023';
  end if;
end;
$$;

create or replace function public.horse_rarity_from_wins(p_wins integer)
returns text
language plpgsql
immutable
as $$
begin
  if coalesce(p_wins, 0) >= 30 then
    return 'legendary';
  end if;
  if coalesce(p_wins, 0) >= 15 then
    return 'epic';
  end if;
  if coalesce(p_wins, 0) >= 5 then
    return 'rare';
  end if;
  return 'common';
end;
$$;

create or replace function public.horse_refresh_rarity(p_horse_id uuid)
returns public.horses
language plpgsql
security definer
set search_path = public
as $$
declare
  wins_count integer := 0;
  horse_record public.horses%rowtype;
begin
  select count(*)::integer
  into wins_count
  from public.horse_races hr
  where hr.status = 'completed'
    and hr.winner_horse_id = p_horse_id;

  update public.horses
  set rarity = public.horse_rarity_from_wins(wins_count)
  where horse_id = p_horse_id
  returning * into horse_record;

  return horse_record;
end;
$$;

do $$
declare
  horse_row record;
begin
  for horse_row in
    select h.horse_id
    from public.horses h
  loop
    perform public.horse_refresh_rarity(horse_row.horse_id);
  end loop;
end $$;

create or replace function public.horse_get_settings_snapshot()
returns jsonb
language sql
stable
set search_path = public
as $$
  select jsonb_build_object(
    'settings', (select to_jsonb(s) from public.horse_race_settings s where s.settings_id = 1),
    'horses', (
      select coalesce(jsonb_agg(to_jsonb(h) order by h.sort_order asc, h.created_at asc), '[]'::jsonb)
      from public.horses h
      where h.enabled = true
    )
  );
$$;

create or replace function public.horse_create_race(p_created_by uuid default null)
returns public.horse_races
language plpgsql
security definer
set search_path = public
as $$
declare
  settings_record public.horse_race_settings%rowtype;
  created_race public.horse_races%rowtype;
  snapshot jsonb;
begin
  select * into settings_record from public.horse_race_settings where settings_id = 1 for update;

  if not found then
    insert into public.horse_race_settings (settings_id) values (1)
    returning * into settings_record;
  end if;

  if settings_record.enabled is false then
    raise exception 'Horse racing is disabled' using errcode = '22023';
  end if;

  perform public.horse_validate_horses_config();
  snapshot := public.horse_get_settings_snapshot();

  insert into public.horse_races (
    status,
    winner_horse_id,
    horses_snapshot,
    settings_version,
    betting_started_at,
    betting_ends_at,
    created_by
  )
  values (
    'betting',
    null,
    snapshot->'horses',
    settings_record.version,
    now(),
    now() + make_interval(secs => settings_record.betting_duration),
    p_created_by
  )
  returning * into created_race;

  return created_race;
end;
$$;

create or replace function public.horse_calculate_winner(p_race_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  race_record public.horse_races%rowtype;
  horse_item record;
  total_weight numeric(18,6) := 0;
  random_point numeric(18,6);
  cumulative numeric(18,6) := 0;
  picked_horse_id uuid;
begin
  select * into race_record
  from public.horse_races
  where race_id = p_race_id
  for update;

  if not found then
    raise exception 'Race not found' using errcode = 'P0002';
  end if;

  for horse_item in
    select
      (h.value->>'horse_id')::uuid as horse_id,
      coalesce((h.value->>'win_probability')::numeric, 0) as win_probability
    from jsonb_array_elements(race_record.horses_snapshot) h
  loop
    total_weight := total_weight + greatest(horse_item.win_probability, 0);
  end loop;

  if total_weight <= 0 then
    raise exception 'No valid horse probability in race snapshot' using errcode = '22023';
  end if;

  random_point := random() * total_weight;

  for horse_item in
    select
      (h.value->>'horse_id')::uuid as horse_id,
      coalesce((h.value->>'win_probability')::numeric, 0) as win_probability
    from jsonb_array_elements(race_record.horses_snapshot) h
    order by coalesce((h.value->>'sort_order')::integer, 0) asc
  loop
    cumulative := cumulative + greatest(horse_item.win_probability, 0);

    if random_point <= cumulative then
      picked_horse_id := horse_item.horse_id;
      exit;
    end if;
  end loop;

  if picked_horse_id is null then
    select (h.value->>'horse_id')::uuid
    into picked_horse_id
    from jsonb_array_elements(race_record.horses_snapshot) h
    limit 1;
  end if;

  return picked_horse_id;
end;
$$;

create or replace function public.horse_refresh_player_stats(p_user_id uuid)
returns public.horse_player_stats
language plpgsql
security definer
set search_path = public
as $$
declare
  stats_record public.horse_player_stats%rowtype;
  account text;
  dname text;
  avatar text;
  longest_streak integer := 0;
  current_streak integer := 0;
  streak_count integer := 0;
  bet_row record;
begin
  select u.account_name, u.display_name, u.avatar_url
  into account, dname, avatar
  from public.users u
  where u.uid = p_user_id;

  for bet_row in
    select hb.result
    from public.horse_bets hb
    where hb.user_id = p_user_id
      and hb.status = 'settled'
    order by hb.settled_at asc nulls last, hb.created_at asc
  loop
    if bet_row.result = 'win' then
      streak_count := streak_count + 1;
      longest_streak := greatest(longest_streak, streak_count);
    else
      streak_count := 0;
    end if;
  end loop;

  streak_count := 0;
  for bet_row in
    select hb.result
    from public.horse_bets hb
    where hb.user_id = p_user_id
      and hb.status = 'settled'
    order by hb.settled_at desc nulls last, hb.created_at desc
  loop
    if bet_row.result = 'win' then
      streak_count := streak_count + 1;
    else
      exit;
    end if;
  end loop;
  current_streak := streak_count;

  insert into public.horse_player_stats (
    user_id,
    account_name,
    display_name,
    avatar_url,
    total_winnings,
    biggest_win,
    total_bets,
    win_count,
    best_streak,
    current_streak,
    updated_at
  )
  select
    p_user_id,
    coalesce(account, 'player'),
    coalesce(dname, 'Player'),
    avatar,
    coalesce(sum(case when hb.status = 'settled' and hb.result = 'win' then hb.points_change else 0 end), 0)::bigint,
    coalesce(max(case when hb.status = 'settled' and hb.result = 'win' then hb.points_change else 0 end), 0)::integer,
    coalesce(count(*) filter (where hb.status = 'settled'), 0)::integer,
    coalesce(count(*) filter (where hb.status = 'settled' and hb.result = 'win'), 0)::integer,
    longest_streak,
    current_streak,
    now()
  from public.horse_bets hb
  where hb.user_id = p_user_id
  on conflict (user_id) do update
    set account_name = excluded.account_name,
        display_name = excluded.display_name,
        avatar_url = excluded.avatar_url,
        total_winnings = excluded.total_winnings,
        biggest_win = excluded.biggest_win,
        total_bets = excluded.total_bets,
        win_count = excluded.win_count,
        best_streak = excluded.best_streak,
        current_streak = excluded.current_streak,
        updated_at = excluded.updated_at
  returning * into stats_record;

  return stats_record;
end;
$$;
create or replace function public.horse_settle_race(p_race_id uuid, p_admin_id uuid default null)
returns public.horse_races
language plpgsql
security definer
set search_path = public
as $$
declare
  race_record public.horse_races%rowtype;
  bet_record public.horse_bets%rowtype;
  user_record public.users%rowtype;
  is_win boolean;
  payout_amount integer;
  delta integer;
  next_points integer;
  next_locked integer;
begin
  select * into race_record
  from public.horse_races
  where race_id = p_race_id
  for update;

  if not found then
    raise exception 'Race not found' using errcode = 'P0002';
  end if;

  if race_record.status = 'completed' then
    return race_record;
  end if;

  if race_record.winner_horse_id is null then
    raise exception 'Winner is not selected' using errcode = '22023';
  end if;

  for bet_record in
    select *
    from public.horse_bets hb
    where hb.race_id = race_record.race_id
      and hb.status = 'pending'
    order by hb.created_at asc
    for update
  loop
    select * into user_record
    from public.users u
    where u.uid = bet_record.user_id
    for update;

    is_win := bet_record.horse_id = race_record.winner_horse_id;
    payout_amount := case when is_win then floor(bet_record.bet_amount::numeric * bet_record.odds_multiplier)::integer else 0 end;
    delta := case when is_win then payout_amount else -bet_record.bet_amount end;

    next_points := user_record.points + delta;
    next_locked := greatest(0, user_record.locked_points - bet_record.bet_amount);

    update public.users
    set points = next_points,
        locked_points = next_locked,
        total_bets = total_bets + 1,
        total_wins = total_wins + case when is_win then 1 else 0 end,
        total_losses = total_losses + case when is_win then 0 else 1 end,
        total_points_won = total_points_won + case when is_win then delta else 0 end,
        total_points_lost = total_points_lost + case when is_win then 0 else bet_record.bet_amount end,
        points_updated_at = now()
    where uid = user_record.uid;

    update public.horse_bets
    set status = 'settled',
        result = case when is_win then 'win' else 'lose' end,
        payout = payout_amount,
        points_before = user_record.points,
        points_after = next_points,
        points_change = delta,
        settled_at = now()
    where bet_id = bet_record.bet_id;

    insert into public.points_transactions (
      user_id,
      game_type,
      type,
      amount,
      points_before,
      points_after,
      locked_before,
      locked_after,
      bet_id,
      note,
      created_at
    )
    values (
      user_record.uid,
      'horse_racing',
      case when is_win then 'horse_bet_win' else 'horse_bet_loss' end,
      delta,
      user_record.points,
      next_points,
      user_record.locked_points,
      next_locked,
      null,
      case
        when is_win then 'Horse race win settlement; horse_bet_id=' || bet_record.bet_id::text
        else 'Horse race loss settlement; horse_bet_id=' || bet_record.bet_id::text
      end,
      now()
    );

    if is_win then
      insert into public.horse_chat_messages (
        user_id,
        display_name,
        avatar,
        role,
        vip_level,
        text,
        is_system,
        created_at
      )
      values (
        user_record.uid,
        'System',
        null,
        'system',
        0,
        user_record.display_name || ' just won with ' || coalesce((select h.name from public.horses h where h.horse_id = race_record.winner_horse_id), 'Unknown Horse') || ' 🔥',
        true,
        now()
      );
    end if;

    perform public.horse_refresh_player_stats(user_record.uid);
  end loop;

  update public.horse_races
  set status = 'completed',
      ended_at = now(),
      race_ends_at = coalesce(race_ends_at, now())
  where race_id = race_record.race_id
  returning * into race_record;

  if race_record.winner_horse_id is not null then
    perform public.horse_refresh_rarity(race_record.winner_horse_id);
  end if;

  return race_record;
end;
$$;

create or replace function public.horse_create_next_race()
returns public.horse_races
language plpgsql
security definer
set search_path = public
as $$
declare
  active_race public.horse_races%rowtype;
begin
  select * into active_race
  from public.horse_races
  where status in ('betting', 'locked', 'racing')
  order by created_at desc
  limit 1;

  if found then
    return active_race;
  end if;

  return public.horse_create_race(null);
end;
$$;

create or replace function public.horse_tick_rounds()
returns public.horse_races
language plpgsql
security definer
set search_path = public
as $$
declare
  active_race public.horse_races%rowtype;
  settings_record public.horse_race_settings%rowtype;
  winner_id uuid;
begin
  perform pg_advisory_xact_lock(hashtext('horse_racing_tick_v1'));

  select * into settings_record from public.horse_race_settings where settings_id = 1;

  if settings_record.enabled is false then
    return null;
  end if;

  select * into active_race
  from public.horse_races
  where status in ('betting', 'locked', 'racing')
  order by created_at desc
  limit 1
  for update;

  if not found then
    return public.horse_create_race(null);
  end if;

  if active_race.status = 'betting' and now() >= active_race.betting_ends_at then
    winner_id := public.horse_calculate_winner(active_race.race_id);

    update public.horse_races
    set status = 'locked',
        winner_horse_id = winner_id,
        locked_at = now(),
        lock_ends_at = now() + interval '1 second',
        race_started_at = null,
        race_ends_at = null,
        started_at = null
    where race_id = active_race.race_id
    returning * into active_race;

    return active_race;
  end if;

  if active_race.status = 'locked' and now() >= coalesce(active_race.lock_ends_at, active_race.locked_at, now()) then
    update public.horse_races
    set status = 'racing',
        race_started_at = now(),
        race_ends_at = now() + make_interval(secs => settings_record.race_duration),
        started_at = now()
    where race_id = active_race.race_id
    returning * into active_race;

    return active_race;
  end if;

  if active_race.status = 'racing' and now() >= coalesce(active_race.race_ends_at, now()) then
    active_race := public.horse_settle_race(active_race.race_id, null);
    perform public.horse_create_race(null);
    return active_race;
  end if;

  return active_race;
end;
$$;

create or replace function public.horse_get_public_state()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  settings_record public.horse_race_settings%rowtype;
  active_race public.horse_races%rowtype;
  recent_races jsonb;
  top_bettors jsonb;
  winners jsonb;
begin
  select * into settings_record from public.horse_race_settings where settings_id = 1;

  if not found then
    insert into public.horse_race_settings (settings_id) values (1) returning * into settings_record;
  end if;

  if settings_record.enabled then
    begin
      active_race := public.horse_create_next_race();
    exception
      when others then
        select * into active_race
        from public.horse_races
        where status in ('betting', 'locked', 'racing')
        order by created_at desc
        limit 1;
    end;
  else
    select * into active_race
    from public.horse_races
    where status in ('betting', 'locked', 'racing')
    order by created_at desc
    limit 1;
  end if;

  select coalesce(jsonb_agg(to_jsonb(r) order by r.created_at desc), '[]'::jsonb)
  into recent_races
  from (
    select hr.*
    from public.horse_races hr
    order by hr.created_at desc
    limit 20
  ) r;

  select coalesce(jsonb_agg(to_jsonb(b) order by b.total_amount desc), '[]'::jsonb)
  into top_bettors
  from (
    select
      hb.user_id,
      u.account_name,
      u.display_name,
      u.avatar_url,
      sum(hb.bet_amount)::bigint as total_amount
    from public.horse_bets hb
    join public.users u on u.uid = hb.user_id
    where hb.created_at >= now() - interval '24 hours'
    group by hb.user_id, u.account_name, u.display_name, u.avatar_url
    order by total_amount desc
    limit 10
  ) b;

  select coalesce(jsonb_agg(to_jsonb(w) order by w.ended_at desc), '[]'::jsonb)
  into winners
  from (
    select
      hr.race_id,
      hr.race_number,
      hr.winner_horse_id,
      h.name as winner_name,
      h.avatar as winner_avatar,
      hr.ended_at
    from public.horse_races hr
    left join public.horses h on h.horse_id = hr.winner_horse_id
    where hr.status = 'completed'
    order by hr.ended_at desc nulls last
    limit 10
  ) w;

  return jsonb_build_object(
    'settings', to_jsonb(settings_record),
    'horses', (
      select coalesce(jsonb_agg(to_jsonb(h) order by h.sort_order asc, h.created_at asc), '[]'::jsonb)
      from public.horses h
      where h.enabled = true
    ),
    'active_race', case when active_race.race_id is null then null else to_jsonb(active_race) end,
    'recent_races', recent_races,
    'recent_winners', winners,
    'top_bettors', top_bettors
  );
end;
$$;

create or replace function public.horse_get_recent_races(p_limit integer default 30)
returns setof public.horse_races
language sql
stable
security definer
set search_path = public
as $$
  select *
  from public.horse_races
  order by created_at desc
  limit greatest(1, least(coalesce(p_limit, 30), 100));
$$;

create or replace function public.horse_get_recent_winners(p_limit integer default 20)
returns table (
  race_id uuid,
  race_number bigint,
  winner_horse_id uuid,
  winner_name text,
  winner_avatar text,
  ended_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    hr.race_id,
    hr.race_number,
    hr.winner_horse_id,
    h.name as winner_name,
    h.avatar as winner_avatar,
    hr.ended_at
  from public.horse_races hr
  left join public.horses h on h.horse_id = hr.winner_horse_id
  where hr.status = 'completed'
  order by hr.ended_at desc nulls last
  limit greatest(1, least(coalesce(p_limit, 20), 100));
$$;
create or replace function public.horse_get_leaderboard(p_limit integer default 20)
returns setof public.horse_player_stats
language sql
stable
security definer
set search_path = public
as $$
  select *
  from public.horse_player_stats
  order by total_winnings desc, biggest_win desc, updated_at asc
  limit greatest(1, least(coalesce(p_limit, 20), 100));
$$;

create or replace function public.horse_get_recent_chat(p_limit integer default 100)
returns setof public.horse_chat_messages
language sql
stable
security definer
set search_path = public
as $$
  select *
  from public.horse_chat_messages
  where is_deleted = false
  order by created_at desc
  limit greatest(1, least(coalesce(p_limit, 100), 200));
$$;

create or replace function public.horse_send_chat_message(
  p_session_token text,
  p_text text
)
returns public.horse_chat_messages
language plpgsql
security definer
set search_path = public
as $$
declare
  current_uid uuid := public.get_session_user_id(p_session_token);
  profile public.users%rowtype;
  message_text text := trim(coalesce(p_text, ''));
  created_message public.horse_chat_messages%rowtype;
begin
  if message_text = '' or char_length(message_text) > 300 then
    raise exception 'Message must be between 1 and 300 characters' using errcode = '22023';
  end if;

  select * into profile from public.users where uid = current_uid;

  if not found then
    raise exception 'User profile not found' using errcode = 'P0002';
  end if;

  if profile.is_banned then
    raise exception 'Account is banned' using errcode = '42501';
  end if;

  insert into public.horse_chat_messages (
    user_id,
    display_name,
    avatar,
    role,
    vip_level,
    text,
    is_system,
    created_at
  )
  values (
    current_uid,
    profile.display_name,
    profile.avatar_url,
    coalesce(nullif(profile.role, ''), 'user'),
    profile.vip_level,
    message_text,
    false,
    now()
  )
  returning * into created_message;

  return created_message;
end;
$$;

create or replace function public.horse_get_my_bets(p_session_token text, p_limit integer default 50)
returns setof public.horse_bets
language plpgsql
security definer
set search_path = public
as $$
declare
  current_uid uuid := public.get_session_user_id(p_session_token);
begin
  return query
  select *
  from public.horse_bets hb
  where hb.user_id = current_uid
  order by hb.created_at desc
  limit greatest(1, least(coalesce(p_limit, 50), 200));
end;
$$;

create or replace function public.horse_place_bet(
  p_session_token text,
  p_horse_id uuid,
  p_bet_amount integer
)
returns public.horse_bets
language plpgsql
security definer
set search_path = public
as $$
declare
  current_uid uuid := public.get_session_user_id(p_session_token);
  profile public.users%rowtype;
  settings_record public.horse_race_settings%rowtype;
  active_race public.horse_races%rowtype;
  horse_record public.horses%rowtype;
  existing_bet public.horse_bets%rowtype;
  updated_bet public.horse_bets%rowtype;
  locked_before integer;
begin
  perform public.horse_tick_rounds();

  select * into settings_record
  from public.horse_race_settings
  where settings_id = 1;

  if settings_record.enabled is false then
    raise exception 'Horse racing is disabled' using errcode = '22023';
  end if;

  if p_bet_amount is null or p_bet_amount < settings_record.min_bet or p_bet_amount > settings_record.max_bet then
    raise exception 'Bet amount must be between % and %', settings_record.min_bet, settings_record.max_bet using errcode = '22023';
  end if;

  select * into active_race
  from public.horse_races hr
  where hr.status = 'betting'
  order by hr.created_at desc
  limit 1
  for update;

  if not found then
    active_race := public.horse_create_next_race();
    select * into active_race
    from public.horse_races hr
    where hr.race_id = active_race.race_id
    for update;
  end if;

  if active_race.status <> 'betting' or now() >= active_race.betting_ends_at then
    raise exception 'Betting is closed for this race' using errcode = '22023';
  end if;

  select * into horse_record
  from public.horses h
  where h.horse_id = p_horse_id
    and h.enabled = true;

  if not found then
    raise exception 'Horse is not available for betting' using errcode = '22023';
  end if;

  if horse_record.odds_multiplier < 1 then
    raise exception 'Horse odds multiplier is invalid (< 1), please contact admin' using errcode = '22023';
  end if;

  select * into profile
  from public.users u
  where u.uid = current_uid
  for update;

  if not found then
    raise exception 'User profile not found' using errcode = 'P0002';
  end if;

  if profile.is_banned then
    raise exception 'Account is banned' using errcode = '42501';
  end if;

  if profile.points - profile.locked_points < p_bet_amount then
    raise exception 'Not enough available points' using errcode = '22023';
  end if;

  locked_before := profile.locked_points;

  select * into existing_bet
  from public.horse_bets hb
  where hb.race_id = active_race.race_id
    and hb.user_id = current_uid
    and hb.horse_id = p_horse_id
    and hb.status = 'pending'
  for update;

  if found then
    update public.horse_bets
    set bet_amount = existing_bet.bet_amount + p_bet_amount,
        odds_multiplier = horse_record.odds_multiplier
    where bet_id = existing_bet.bet_id
    returning * into updated_bet;
  else
    insert into public.horse_bets (
      race_id,
      user_id,
      horse_id,
      bet_amount,
      odds_multiplier,
      status,
      result,
      payout,
      points_change
    )
    values (
      active_race.race_id,
      current_uid,
      p_horse_id,
      p_bet_amount,
      horse_record.odds_multiplier,
      'pending',
      null,
      0,
      0
    )
    returning * into updated_bet;
  end if;

  update public.users
  set locked_points = public.users.locked_points + p_bet_amount,
      points_updated_at = now()
  where uid = current_uid
  returning * into profile;

  insert into public.points_transactions (
    user_id,
    game_type,
    type,
    amount,
    points_before,
    points_after,
    locked_before,
    locked_after,
    bet_id,
    note,
    created_at
  )
  values (
    current_uid,
    'horse_racing',
    'horse_bet_lock',
    p_bet_amount,
    profile.points,
    profile.points,
    locked_before,
    profile.locked_points,
    null,
    'Horse race bet locked; horse_bet_id=' || updated_bet.bet_id::text,
    now()
  );

  return updated_bet;
end;
$$;
create or replace function public.admin_horse_get_state(p_session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.assert_admin(p_session_token);
  return public.horse_get_public_state();
end;
$$;

create or replace function public.admin_horse_update_settings(
  p_session_token text,
  p_enabled boolean,
  p_min_bet integer,
  p_max_bet integer,
  p_betting_duration integer,
  p_race_duration integer,
  p_expected_version integer default null
)
returns public.horse_race_settings
language plpgsql
security definer
set search_path = public
as $$
declare
  admin_uid uuid := public.assert_admin(p_session_token);
  settings_record public.horse_race_settings%rowtype;
  updated_settings public.horse_race_settings%rowtype;
begin
  select * into settings_record
  from public.horse_race_settings
  where settings_id = 1
  for update;

  if not found then
    insert into public.horse_race_settings (settings_id)
    values (1)
    returning * into settings_record;
  end if;

  if p_expected_version is not null and settings_record.version <> p_expected_version then
    raise exception 'Horse settings changed by another admin (expected %, actual %)', p_expected_version, settings_record.version using errcode = '40001';
  end if;

  if p_min_bet < 1 or p_max_bet < p_min_bet then
    raise exception 'Invalid min/max bet settings' using errcode = '22023';
  end if;

  if p_betting_duration < 10 or p_betting_duration > 180 then
    raise exception 'Betting duration must be 10-180 seconds' using errcode = '22023';
  end if;

  if p_race_duration < 10 or p_race_duration > 180 then
    raise exception 'Race duration must be 10-180 seconds' using errcode = '22023';
  end if;

  update public.horse_race_settings
  set enabled = p_enabled,
      min_bet = p_min_bet,
      max_bet = p_max_bet,
      betting_duration = p_betting_duration,
      race_duration = p_race_duration,
      updated_by = admin_uid,
      updated_at = now(),
      version = settings_record.version + 1
  where settings_id = 1
  returning * into updated_settings;

  insert into public.admin_logs (admin_id, action, details)
  values (
    admin_uid,
    'admin_horse_update_settings',
    jsonb_build_object(
      'before', to_jsonb(settings_record),
      'after', to_jsonb(updated_settings)
    )
  );

  return updated_settings;
end;
$$;

create or replace function public.admin_horse_upsert_horse(
  p_session_token text,
  p_horse_id uuid,
  p_name text,
  p_avatar text,
  p_speed_rating integer,
  p_rarity text,
  p_odds_multiplier numeric,
  p_win_probability numeric,
  p_enabled boolean,
  p_sort_order integer
)
returns public.horses
language plpgsql
security definer
set search_path = public
as $$
declare
  admin_uid uuid := public.assert_admin(p_session_token);
  normalized_name text := trim(coalesce(p_name, ''));
  horse_record public.horses%rowtype;
  before_snapshot jsonb;
begin
  if normalized_name = '' then
    raise exception 'Horse name is required' using errcode = '22023';
  end if;

  if p_speed_rating < 1 or p_speed_rating > 100 then
    raise exception 'Speed rating must be 1-100' using errcode = '22023';
  end if;

  if p_odds_multiplier < 1 then
    raise exception 'Odds multiplier must be >= 1' using errcode = '22023';
  end if;

  if p_win_probability < 0 then
    raise exception 'Probability must be >= 0' using errcode = '22023';
  end if;

  if p_horse_id is not null then
    select to_jsonb(h) into before_snapshot
    from public.horses h
    where h.horse_id = p_horse_id;

    update public.horses
    set name = normalized_name,
        avatar = nullif(trim(coalesce(p_avatar, '')), ''),
        speed_rating = p_speed_rating,
        odds_multiplier = p_odds_multiplier,
        win_probability = p_win_probability,
        enabled = p_enabled,
        sort_order = coalesce(p_sort_order, 0)
    where horse_id = p_horse_id
    returning * into horse_record;

    if not found then
      raise exception 'Horse not found' using errcode = 'P0002';
    end if;
  else
    insert into public.horses (
      name,
      avatar,
      speed_rating,
      rarity,
      odds_multiplier,
      win_probability,
      enabled,
      sort_order
    )
    values (
      normalized_name,
      nullif(trim(coalesce(p_avatar, '')), ''),
      p_speed_rating,
      'common',
      p_odds_multiplier,
      p_win_probability,
      p_enabled,
      coalesce(p_sort_order, 0)
    )
    returning * into horse_record;

    before_snapshot := null;
  end if;

  horse_record := public.horse_refresh_rarity(horse_record.horse_id);
  perform public.horse_validate_horses_config();

  insert into public.admin_logs (admin_id, action, details)
  values (
    admin_uid,
    'admin_horse_upsert_horse',
    jsonb_build_object(
      'before', before_snapshot,
      'after', to_jsonb(horse_record)
    )
  );

  return horse_record;
end;
$$;

create or replace function public.admin_horse_delete_horse(
  p_session_token text,
  p_horse_id uuid
)
returns public.horses
language plpgsql
security definer
set search_path = public
as $$
declare
  admin_uid uuid := public.assert_admin(p_session_token);
  horse_record public.horses%rowtype;
begin
  select * into horse_record
  from public.horses
  where horse_id = p_horse_id
  for update;

  if not found then
    raise exception 'Horse not found' using errcode = 'P0002';
  end if;

  delete from public.horses
  where horse_id = p_horse_id;

  perform public.horse_validate_horses_config();

  insert into public.admin_logs (admin_id, action, details)
  values (
    admin_uid,
    'admin_horse_delete_horse',
    jsonb_build_object('horse', to_jsonb(horse_record))
  );

  return horse_record;
end;
$$;

create or replace function public.admin_horse_force_end_race(
  p_session_token text,
  p_race_id uuid,
  p_note text default null
)
returns public.horse_races
language plpgsql
security definer
set search_path = public
as $$
declare
  admin_uid uuid := public.assert_admin(p_session_token);
  race_record public.horse_races%rowtype;
begin
  select * into race_record
  from public.horse_races
  where race_id = p_race_id
  for update;

  if not found then
    raise exception 'Race not found' using errcode = 'P0002';
  end if;

  if race_record.status = 'completed' then
    return race_record;
  end if;

  if race_record.winner_horse_id is null then
    update public.horse_races
    set winner_horse_id = public.horse_calculate_winner(race_record.race_id),
        locked_at = coalesce(locked_at, now()),
        lock_ends_at = now(),
        status = 'racing',
        race_started_at = coalesce(race_started_at, now()),
        race_ends_at = now(),
        started_at = coalesce(started_at, now())
    where race_id = race_record.race_id
    returning * into race_record;
  end if;

  race_record := public.horse_settle_race(race_record.race_id, admin_uid);
  perform public.horse_create_race(admin_uid);

  insert into public.admin_logs (admin_id, action, target_round_id, details)
  values (
    admin_uid,
    'admin_horse_force_end_race',
    race_record.race_id,
    jsonb_build_object('note', p_note)
  );

  return race_record;
end;
$$;

create or replace function public.admin_horse_get_live_stats(p_session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.assert_admin(p_session_token);

  return jsonb_build_object(
    'active_users', (
      select coalesce(count(distinct hb.user_id), 0)
      from public.horse_bets hb
      where hb.created_at >= now() - interval '10 minutes'
    ),
    'betting_statistics', (
      select jsonb_build_object(
        'total_bets_24h', coalesce(count(*), 0),
        'total_amount_24h', coalesce(sum(hb.bet_amount), 0),
        'settled_24h', coalesce(count(*) filter (where hb.status = 'settled'), 0),
        'wins_24h', coalesce(count(*) filter (where hb.result = 'win'), 0)
      )
      from public.horse_bets hb
      where hb.created_at >= now() - interval '24 hours'
    ),
    'recent_admin_logs', (
      select coalesce(jsonb_agg(to_jsonb(l) order by l.created_at desc), '[]'::jsonb)
      from (
        select al.log_id, al.admin_id, al.action, al.target_round_id, al.details, al.created_at
        from public.admin_logs al
        where al.action like 'admin_horse_%'
        order by al.created_at desc
        limit 30
      ) l
    )
  );
end;
$$;
-- Permissions.
revoke all on public.horse_race_settings from anon, authenticated;
revoke all on public.horses from anon, authenticated;
revoke all on public.horse_races from anon, authenticated;
revoke all on public.horse_bets from anon, authenticated;
revoke all on public.horse_chat_messages from anon, authenticated;
revoke all on public.horse_player_stats from anon, authenticated;

revoke all on function public.horse_validate_horses_config() from public, anon, authenticated;
revoke all on function public.horse_rarity_from_wins(integer) from public, anon, authenticated;
revoke all on function public.horse_refresh_rarity(uuid) from public, anon, authenticated;
revoke all on function public.horse_get_settings_snapshot() from public, anon, authenticated;
revoke all on function public.horse_create_race(uuid) from public, anon, authenticated;
revoke all on function public.horse_calculate_winner(uuid) from public, anon, authenticated;
revoke all on function public.horse_settle_race(uuid, uuid) from public, anon, authenticated;
revoke all on function public.horse_create_next_race() from public, anon, authenticated;
revoke all on function public.horse_refresh_player_stats(uuid) from public, anon, authenticated;
revoke all on function public.horse_place_bet(text, uuid, integer) from public, anon, authenticated;
revoke all on function public.horse_tick_rounds() from public, anon, authenticated;
revoke all on function public.horse_get_public_state() from public, anon, authenticated;
revoke all on function public.horse_get_recent_races(integer) from public, anon, authenticated;
revoke all on function public.horse_get_recent_winners(integer) from public, anon, authenticated;
revoke all on function public.horse_get_leaderboard(integer) from public, anon, authenticated;
revoke all on function public.horse_get_recent_chat(integer) from public, anon, authenticated;
revoke all on function public.horse_send_chat_message(text, text) from public, anon, authenticated;
revoke all on function public.horse_get_my_bets(text, integer) from public, anon, authenticated;
revoke all on function public.admin_horse_get_state(text) from public, anon, authenticated;
revoke all on function public.admin_horse_update_settings(text, boolean, integer, integer, integer, integer, integer) from public, anon, authenticated;
revoke all on function public.admin_horse_upsert_horse(text, uuid, text, text, integer, text, numeric, numeric, boolean, integer) from public, anon, authenticated;
revoke all on function public.admin_horse_delete_horse(text, uuid) from public, anon, authenticated;
revoke all on function public.admin_horse_force_end_race(text, uuid, text) from public, anon, authenticated;
revoke all on function public.admin_horse_get_live_stats(text) from public, anon, authenticated;

grant select on public.horse_races to anon, authenticated;
grant select on public.horse_bets to anon, authenticated;
grant select on public.horse_chat_messages to anon, authenticated;
grant select on public.horse_player_stats to anon, authenticated;
grant select on public.horses to anon, authenticated;
grant execute on function public.horse_place_bet(text, uuid, integer) to anon, authenticated;
grant execute on function public.horse_tick_rounds() to anon, authenticated;
grant execute on function public.horse_get_public_state() to anon, authenticated;
grant execute on function public.horse_get_recent_races(integer) to anon, authenticated;
grant execute on function public.horse_get_recent_winners(integer) to anon, authenticated;
grant execute on function public.horse_get_leaderboard(integer) to anon, authenticated;
grant execute on function public.horse_get_recent_chat(integer) to anon, authenticated;
grant execute on function public.horse_send_chat_message(text, text) to anon, authenticated;
grant execute on function public.horse_get_my_bets(text, integer) to anon, authenticated;
grant execute on function public.admin_horse_get_state(text) to anon, authenticated;
grant execute on function public.admin_horse_update_settings(text, boolean, integer, integer, integer, integer, integer) to anon, authenticated;
grant execute on function public.admin_horse_upsert_horse(text, uuid, text, text, integer, text, numeric, numeric, boolean, integer) to anon, authenticated;
grant execute on function public.admin_horse_delete_horse(text, uuid) to anon, authenticated;
grant execute on function public.admin_horse_force_end_race(text, uuid, text) to anon, authenticated;
grant execute on function public.admin_horse_get_live_stats(text) to anon, authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'horse_race_settings'
  ) then
    alter publication supabase_realtime add table public.horse_race_settings;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'horses'
  ) then
    alter publication supabase_realtime add table public.horses;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'horse_races'
  ) then
    alter publication supabase_realtime add table public.horse_races;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'horse_bets'
  ) then
    alter publication supabase_realtime add table public.horse_bets;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'horse_chat_messages'
  ) then
    alter publication supabase_realtime add table public.horse_chat_messages;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'horse_player_stats'
  ) then
    alter publication supabase_realtime add table public.horse_player_stats;
  end if;
end $$;

notify pgrst, 'reload schema';
